name: Docker Build and Push

# Déclencheur du workflow
on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche main
  pull_request:
    branches:
      - main  # Déclenche le workflow lors d'une pull request sur la branche main

# Environnement d'exécution
jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Utilise un secret GitHub
          password: ${{ secrets.DOCKER_HUB_TOKEN }}     # Utilise un secret GitHub

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/quelpoke:1.0 .

      # Étape 4 : Pousser l'image Docker vers Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quelpoke:1.0
